### ISSUE TITLE
public methods can't be resolved

### ISSUE THREAD

**Issue by liftercoder** [i-e-b/MvcIntegrationTestFramework#2]
This is the most promising integration framework I've seen for MVC applications, everywhere else talks about Web API, which not all of us use, especially legacy applications. So thank you for continuing this and sorry for opening an issue but I can't for the life of me work out what's going on:

I'm using VS 2015 and 2017
I'm using the default Microsoft test project in VS
I've installed the framework using NuGet and have referenced the appropriate namespaces in the project.
I'm targeting .NET 4.5

Yet when I try to use AppHost.Simulate VS complains that the type doesn't contain the method, despite it being public and static.

Any ideas? I must be missing something simple.

**Comment by i-e-b** [comment]
Do you have a small sample Solution I can look at? Also, can you run the tests in the MvcIntegrationTestFramework project itself?

**Comment by i-e-b** [comment]
Closing: can't replicate and no feedback
