### ISSUE TITLE
Warning: System.AppDomainUnloadedException when running test

### ISSUE THREAD

**Issue by dougeff** [i-e-b/MvcIntegrationTestFramework#4]
Hello:

I'm running VS 2015 on my machine and I deploy using Azure Devops.  When I run the tests locally using your framework, everything runs fine with no issues to report.  In Azure, I'm getting this message for each TestFixture:  "Warning: System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain. This can happen if the test(s) started a thread but did not stop it. Make sure that all the threads started by the test(s) are stopped before completion."  This hasn't prevented the tests from being successfully run, however.  I'm just wondering if this is something for me to be concerned with.  A sample TestFixture is attached:

[sample.txt](https://github.com/i-e-b/MvcIntegrationTestFramework/files/2813251/sample.txt)

Thanks for any light you can shed on this.

**Comment by i-e-b** [comment]
Interesting. Can you tell me exactly which version you are using (NuGet version number, or git commit ID)?
Thanks.

**Comment by dougeff** [comment]
Thanks for replying.  It's version 1.0.6.  Should I upgrade?  NuGet says I can get 1.0.8.

**Comment by dougeff** [comment]
Well, I guess you can close this ticket.  I just made another push today to my repo and I got no warnings whatsoever.  I didn't upgrade, and all I did was add another integration test, so it's looking to me that this was an Azure thing.  Azure was crashing 2 days ago, so maybe this issue I had was a side effect of it.  Anyway, looks like nothing for you to do.  Sorry to be a bother.

**Comment by i-e-b** [comment]
No problems, thanks for the feedback. I think there was a bug in earlier versions where it left threads open, so it might be worth upgrading. Let me know if the issue comes back
